[custom.all.webidl]
type = "local"
path = "."
ipkg = "webidl.ipkg"

[custom.all.parser]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:errors"
ipkg   = "parser.ipkg"

[custom.all.parser-webidl]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:errors"
ipkg   = "webidl/parser-webidl.ipkg"
